# Wret Configuration
## Docs: 
## Source: https://github.com/keenguy/wret/

# Site
title: Yong's Blog
subtitle: My personal notes.
author: Gu Yong

# URL
url: http://blog.yonggu.me

copyFiles: [
  'CNAME',
  'assets'
]

# Deployment
deploy:
  type: git
  repo: https://github.com/Keenguy/blog.git
  branch: master

#Custom Setting Start

# Site settings
# SEOTitle: GuYong的博客 | Yong's Blog | Yong Gu's Blog
# email:
# description: ""
# keyword: ""

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
#duoshuo_username: kaijun
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
#ba_track_id: 4cc1f2d8f3067386cc5cdb626a202900
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me


# Sidebar settings
#sidebar: true                           # whether or not using Sidebar.
#sidebar-about-description: "我要成为魔法师!"
#sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
#featured-tags: true                     # whether or not using Feature-Tags
#featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
# friends: [
#     {
#         title: "Kaijun's Blog",
#         href: "http://blog.kaijun.rocks"
#     },{
#         title: "Hux Blog",
#         href: "http://huangxuan.me"
#     },{
#         title: "Foo",
#         href: "#"
#     },{
#         title: "Bar",
#         href: "#"
#     },{
#         title: "Example Friends",
#         href: "#"
#     },{
#         title: "It helps SEO",
#         href: "#"
#     }
# ]


#Custom Setting End



# Directory
# source_dir: source
# public_dir: public
# tag_dir: tags
# archive_dir: archives
# category_dir: categories
# code_dir: downloads/code
# i18n_dir: :lang
# skip_render:



